In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px

gifts=pd.read_csv('ForeignGifts_edu.csv')

>First, I'd be interested to see where the money is currently coming from at UVA. Which contries are we lacking and what types of organizations are donating

In [22]:
pd.set_option('display.max_rows',100)
gifts_to_uva=gifts[gifts['Institution Name']=="University of Virginia"]

In [10]:
gifts_to_uva[['Country of Giftor','Foreign Gift Amount', 'Gift Type', 'Giftor Name']]

,Country of Giftor,Foreign Gift Amount,Gift Type,Giftor Name
26235,ENGLAND,3565,Monetary Gift,West Yorkshire Police
26236,ISRAEL,12265,Contract,CureTech Ltd
26237,ISRAEL,8187,Monetary Gift,Branco Weiss Institute
26238,ISRAEL,6437,Contract,NovoCure Ltd
26239,ISRAEL,216943,Contract,InSightec-Image Guide Treatment Ltd
26240,ISRAEL,12021,Contract,InSightec-Image Guide Treatment Ltd
26241,ISRAEL,55811,Contract,InSightec-Image Guide Treatment Ltd
26242,ISRAEL,10000,Monetary Gift,Atox Bio Ltd.
26243,ENGLAND,9825,Monetary Gift,TauRx Therapeutics Ltd
26244,ISRAEL,6979,Monetary Gift,US-Israel Binational Sci Fdn
26245,ISRAEL,5612,Monetary Gift,US-Israel Binational Sci Fdn
26246,BANGLADESH,310001,Monetary Gift,Intl Ctr for Diarrhoeal Disease
26247,ISRAEL,2650,Contract,BSP-Biological Signal Proc Ltd
26248,ENGLAND,68910,Monetary Gift,Kirkhouse Trust
26249,ENGLAND,321029,Monetary Gift,Charles Aid Foundation
26250,SWEDEN,1500027,Contract,AstraZeneca
26251,SWEDEN,7622,Contract,Orexo AB
26252,JAPAN,265970,Contract,"Honda R & D Co., LTD"
26253,KOREA,131534,Contract,Daegu Gyeongbuk Inst of Sci & Tech
26254,KOREA,249555,Contract,Hyundai Motor Company
26255,ENGLAND,53452,Monetary Gift,Kirkhouse Trust
26256,ENGLAND,300460,Monetary Gift,Charities Aid Foundation
26257,ENGLAND,65633,Monetary Gift,University of Newcastle
26258,SINGAPORE,500000,Monetary Gift,Rainbow Foundation
26259,BANGLADESH,275008,Monetary Gift,Intl. Cntr for Diarrihoeal Disease
26260,KOREA,318537,Contract,Hyundai Motor Company
26261,BANGLADESH,304450,Contract,Intrnl Centre Diarrheal Disease
26262,BANGLADESH,1077948,Contract,Intrnl Centre Diarrheal Disease
26263,BANGLADESH,498,Monetary Gift,Intrnl Centre Diarrheal Disease
26264,BANGLADESH,421278,Contract,Intl. Cntr for Diarrihoeal Disease
26265,THE NETHERLANDS,236681,Contract,Philips Healthcare
26266,ISRAEL,23500,Contract,Galmed Research & Development Ltd
26267,KOREA,41428,Contract,Korea Transport Institute
26268,BANGLADESH,31,Contract,Intl. Cntr for Diarrihoeal Disease
26269,ENGLAND,106196,Contract,University of Liverpool
26270,ENGLAND,3102,Contract,TauRx Therapeutics Ltd.
26271,ENGLAND,68082,Contract,Kirkhouse Trust
26272,ENGLAND,32996,Contract,London School of Economics
26273,ENGLAND,102662,Contract,GW Research Ltd.
26274,SWEDEN,1708021,Contract,AstraZeneca
26275,THE NETHERLANDS,195369,Contract,Genmab B.V.
26276,KOREA,113400,Contract,Daegu Gyeongbuk Inst of Sc& Tech
26277,SWEDEN,29970,Contract,Elekta Instrument AB
26278,BERMUDA,900000,Monetary Gift,Hemera Foundation
26279,KOREA,8333,Contract,Korea Automobile Testing & Research
26280,SWEDEN,5056,Contract,AutoLiv Development AB
26281,ENGLAND,22880,Contract,University of Newcastle
26282,SWEDEN,76695,Contract,Chalmers University of Technology
26283,ISRAEL,263250,Contract,InSightec-Image Guided Treatment Lt
26284,ENGLAND,211622,Monetary Gift,Charities Aid Foundation
26285,FINLAND,277515,Contract,Danisco Sweeteners Oy
26286,ENGLAND,65150,Contract,G. W. Research Ltd
26287,ENGLAND,8933,Contract,London School of Economics
26288,ENGLAND,20927,Monetary Gift,University of Newcastle
26289,ENGLAND,128195,Monetary Gift,Kirkhouse Trust
26290,FINLAND,7500,Contract,FKD Therapies Oy
26291,TANZANIA,640555,Contract,Haydom Lutheran Hospital
26292,FINLAND,370020,Contract,Danisco Sweeteners Oy
26293,RWANDA,284135,Contract,"Republic of Rwanda, Mintr of Health"
26294,ENGLAND,9750,Contract,Adelphi Group Limited
26295,ENGLAND,3071,Monetary Gift,Kirkhouse Trust
26296,GUERNSEY,500000,Monetary Gift,Harvest Group Holding
26297,FRANCE,113478,Contract,"Theraclion, S.A."
26298,ENGLAND,13344,Monetary Gift,Kirkhouse Trust
26299,BANGLADESH,339,Monetary Gift,Intnl Centre for Diarrhoeal Disease
26300,FRANCE,112470,Monetary Gift,Human Frontier Science Program
26301,ENGLAND,7850,Contract,GW Research Ltd
26302,FRANCE,5250,Contract,Biom 'Up
26303,TANZANIA,1100553,Contract,Haydom Lutheran Hospital d/b/a Hayd
26304,ENGLAND,6000,Contract,Emergent Countermeasures Intnl
26305,ENGLAND,8601,Monetary Gift,Kirkhouse Trust
26306,ENGLAND,35056,Contract,GW Research Ltd
26307,ENGLAND,20982,Contract,London School of Economics
26308,ENGLAND,215846,Monetary Gift,Charities Aid Foundation
26309,FRANCE,9350,Contract,Genfit
26310,ENGLAND,7184,Monetary Gift,Kirkhouse Trust
26311,ENGLAND,223,Monetary Gift,University of Newcastle
26312,BANGLADESH,919518,Contract,Intnl Centre for Diarrhoeal Disease
26313,ENGLAND,13519,Contract,GW Research Ltd
26314,FRANCE,9835,Contract,Genfit
26315,ENGLAND,15621,Monetary Gift,Kirkhouse Trust
26316,FINLAND,84376,Contract,Danisco Sweeteners Oy
26317,FINLAND,1493,Contract,FKD Therapies Oy
26318,FINLAND,9060,Contract,FKD Therapies Oy
26319,FINLAND,258420,Contract,Danisco Sweeteners Oy
26320,SWEDEN,207032,Contract,AutoLiv Development AB
26321,TANZANIA,1035339,Contract,Haydom Luther Hospital
26322,GUERNSEY,500000,Monetary Gift,Harvest Group Holding
26323,SWEDEN,207019,Contract,AutoLiv Development AB
26324,SINGAPORE,305000,Monetary Gift,Rainbow Foundation
26325,SWEDEN,166225,Contract,AutoLiv Development AB
26326,BANGLADESH,919518,Contract,International Centre for Diarrhoeal
26327,SWITZERLAND,1000000,Monetary Gift,Lawrence D/ Karin S Howell
26328,SWEDEN,99885,Contract,AutoLiv Development AB
26329,SWITZERLAND,1000000,Monetary Gift,Lawrence D & Karin S Howell
26330,GUERNSEY,500000,Monetary Gift,Harvest Group Holding (PTC Limited)
26331,THE NETHERLANDS,146810,Contract,Pantarhei Oncology BV
26332,THE NETHERLANDS,146810,Contract,Pantarhei Oncology BV

>Lots of reserach companies from a good amount of countries, but UVA is missing a lot of the "heavy hitters" so to speak. No Qatar giving millions at a time. No huge land investments

>Here, I'm making a new dataframe that is grouped by not only the country, but where else they donated to and how much. This is going to be perfect for data exploration.

In [17]:
country_to_school=gifts.groupby(['Country of Giftor','Institution Name']).sum()['Foreign Gift Amount']

In [ ]:
country_to_school=pd.DataFrame(country_to_school)
country_to_school[1:50]

#since this is long, we look at it in chunks

                                                                      Foreign Gift Amount
Country of Giftor Institution Name
AFGHANISTAN       Ohio University                                                  516102
                  University of Illinois at Urbana-Champaign                      1604589
AMERICAN SAMOA    University of Hawaii at Manoa                                   2338347
ANGOLA            University of Colorado Boulder                                   432482
                  University of Oklahoma                                           499908
ANTIGUA           Florida International University                                3435545
ARGENTINA         Brigham Young University                                        1750000
                  Columbia University in the City of New York                      280000
                  Harvard University                                              1258418
                  Johns Hopkins University                                          10425
                  Massachusetts Institute of Technology                           3727609
                  Stanford University                                              900000
                  University of Notre Dame                                         200000
                  University of Washington - Seattle                               337632
ARMENIA           Johns Hopkins University                                            300
AUSTRALIA         Arizona State University                                        1199900
                  California Institute of Technology                              2465432
                  Carnegie Mellon University                                      1148070
                  Catholic University of America (The)                            1307450
                  Columbia University in the City of New York                     1238597
                  Cornell University                                              2014431
                  Duke University                                                  849954
                  Emory University                                                 555184
                  George Mason University                                           44950
                  George Washington University                                     653557
                  Georgia Institute of Technology                                 1261164
                  Harvard University                                              6321092
                  Indiana University - Purdue University Indianap...              1480492
                  Johns Hopkins University                                        3849790
                  Kansas State University                                         1159330
                  Massachusetts Institute of Technology                           7505960
                  Michigan State University                                        709175
                  New Jersey Institute of Technology                              1240106
                  North Carolina State University                                  258653
                  Northeastern University                                       148355497
                  Northern Arizona University                                      403928
                  Ohio State University (The)                                     1092000
                  Oregon Health & Science University                               332197
                  Princeton University                                           12900000
                  Purdue University                                               1500000
                  Rensselaer Polytechnic Institute                                 300000
                  Stanford University                                             2604725
                  Texas Tech University                                           2250000
                  University of Alabama at Birmingham                              608019
                  University of Arizona (The)                                      916308
                  University of California, Berkeley                               812334
                  University of California, Davis                                 2363248
                  University of California, Los Angeles                           2320429
                  University of California, San Diego                             3207794

In [76]:
country_to_school.xs("AUSTRALIA",level="Country of Giftor")
#hmm lets take a look at australia alone. They seem to donate a lot to several bit reserach schools

                                                    Foreign Gift Amount
Institution Name
Arizona State University                                        1199900
California Institute of Technology                              2465432
Carnegie Mellon University                                      1148070
Catholic University of America (The)                            1307450
Columbia University in the City of New York                     1238597
Cornell University                                              2014431
Duke University                                                  849954
Emory University                                                 555184
George Mason University                                           44950
George Washington University                                     653557
Georgia Institute of Technology                                 1261164
Harvard University                                              6321092
Indiana University - Purdue University Indianap...              1480492
Johns Hopkins University                                        3849790
Kansas State University                                         1159330
Massachusetts Institute of Technology                           7505960
Michigan State University                                        709175
New Jersey Institute of Technology                              1240106
North Carolina State University                                  258653
Northeastern University                                       148355497
Northern Arizona University                                      403928
Ohio State University (The)                                     1092000
Oregon Health & Science University                               332197
Princeton University                                           12900000
Purdue University                                               1500000
Rensselaer Polytechnic Institute                                 300000
Stanford University                                             2604725
Texas Tech University                                           2250000
University of Alabama at Birmingham                              608019
University of Arizona (The)                                      916308
University of California, Berkeley                               812334
University of California, Davis                                 2363248
University of California, Los Angeles                           2320429
University of California, San Diego                             3207794
University of Chicago (The)                                     3000000
University of Colorado Boulder                                     1000
University of Colorado Colorado Springs                            2200
University of Florida                                           1106173
University of Georgia                                            770099
University of Illinois at Chicago                               4448217
University of Kentucky                                           250949
University of Louisville                                         150776
University of Maryland, College Park                             328770
University of Michigan - Ann Arbor                               965452
University of Notre Dame                                         875355
University of Pennsylvania                                       393199
University of Pittsburgh                                         136011
University of Rochester                                          324840
University of Southern California                              14400000
University of Texas MD Anderson Cancer Center                    578256
University of Texas at Austin                                   1397961
University of Washington - Seattle                               286135
Virginia Commonwealth University                                 371196
Westminster Theological Seminary                                  10323
Yale University                                                 3382524

>Wow, australia likes to give a lot of money to a lot of different schools. Specifically, they like to give to a lot of big research schools and they're pretty familiar with giving to virginia schools.

Next, seperate out for just australia and look to see who is giving. It's not helpful to talk to the country as a whole. Who specifically do we need to talk to?

In [44]:
australian_giftors=gifts.loc[gifts['Country of Giftor']=='AUSTRALIA'].groupby(gifts['Giftor Name']).sum()[['Institution Name', 'Foreign Gift Amount']]
australian_giftors.head(20)

,Institution Name,Foreign Gift Amount
Giftor Name,,
"ALLEN, C","University of California, Los Angeles",150
"ALONTE, SALLY","University of California, Los Angeles",25
"ANAND, SAURABH","University of California, Los Angeles",50
AUSTRALIAN HEALTH AND NUTRITION ASS,"University of California, San DiegoUniversity ...",347672
"Anand, Saurabh","University of California, Los Angeles",50
Anon. Donor #7,Yale University,281478
Anonymous #10,Yale University,591324
Anonymous #14,Yale University,346627
Anonymous #147,Yale University,1889095
Anonymous #59,Yale University,274000
Arthritis Austrailia,Georgia Institute of Technology,300000
Australian Catholic University,"University of California, San DiegoUniversity ...",1983302
Australian Graduate School of Manag,University of Pennsylvania,393199
Australian Ministry Foreign Affairs,Columbia University in the City of New York,209275
Australian Nat'l Low Emissions Coal,University of Texas at AustinUniversity of Tex...,781861
Australian National University,Northern Arizona UniversityNorthern Arizona Un...,302114
Australian Wool Innovation Limited,North Carolina State University,258653
"BAUKH, SIMON","University of California, Los Angeles",500
"BAUKH, SIMON M","University of California, Los Angeles",500
BCAL Diagnostics Pty Limited,University of Kentucky,250949

> After discovering some patterns in this data, I'm seeing a TON of money is going into health research (which is great since UVA has a huge health research department)

Only small donations though :(

Let's try france

In [73]:
france=gifts.loc[gifts['Country of Giftor']=='FRANCE'].groupby(gifts['Giftor Name']).sum()[['Institution Name', 'Foreign Gift Amount', 'Gift Type']]
france['giftor']=france.index
france

,Institution Name,Foreign Gift Amount,Gift Type,giftor
Giftor Name,,,,
"""BUZZI, STEPHANE""",California Institute of Technology,5043,Contract,"""BUZZI, STEPHANE"""
"""KASPERSKI, TATIANA""",California Institute of Technology,586,Contract,"""KASPERSKI, TATIANA"""
"""RILEY, LEANNE""",California Institute of Technology,3556,Contract,"""RILEY, LEANNE"""
AAV Life,Cornell University,1189505,Contract,AAV Life
AB Science,University of Tennessee,370384,Contract,AB Science
...,...,...,...,...
"Yron, Lionel","University of California, Los Angeles",20,Monetary Gift,"Yron, Lionel"
Yves Saint Laurent SAS,"University of California, Los AngelesUniversit...",20000,Monetary GiftMonetary Gift,Yves Saint Laurent SAS
Zodiac Data Systems,California Institute of Technology,3178,Contract,Zodiac Data Systems
"bioMerieux, Inc","Rutgers, the State University of New JerseyRut...",984977,ContractContract,"bioMerieux, Inc"
École polytechnique fédérale,California Institute of TechnologyCalifornia I...,34257,ContractContractContractContractContractContract,École polytechnique fédérale

>Interesting. It looks like lots of donations from sanofi under different names. Let's group them together

In [74]:
france['giftor']=france['giftor'].str.lower()
mask= france['giftor'].str.contains('sanofi')
france[mask]

,Institution Name,Foreign Gift Amount,Gift Type,giftor
Giftor Name,,,,
SANOFI,University of GeorgiaUniversity of GeorgiaUniv...,7093879,ContractContractContract,sanofi
SANOFI PASTEUR,University of Wisconsin - Madison,610911,Contract,sanofi pasteur
SANOFI PASTEUR LIMITED,University of Colorado DenverUniversity of Col...,53015,ContractContractContract,sanofi pasteur limited
"SANOFI PHARMACEUTICALS, INC.",University of PennsylvaniaUniversity of Pennsy...,1063194,ContractContractContract,"sanofi pharmaceuticals, inc."
"SANOFI PHARMACEUTICALS,INC",University of PennsylvaniaUniversity of Pennsy...,215550,ContractContractContract,"sanofi pharmaceuticals,inc"
"SANOFI PHARMACEUTICALS,INC.",University of PennsylvaniaUniversity of Pennsy...,268072,ContractContractContract,"sanofi pharmaceuticals,inc."
SANOFI S.A.,"University of California, Los AngelesUniversit...",527281,ContractContractContractContractContract,sanofi s.a.
SANOFI SA,"University of California, Los Angeles",556983,Contract,sanofi sa
SANOFI-AVENTIS,California Institute of TechnologyCalifornia I...,434039,ContractContractContractContractContractContra...,sanofi-aventis
SANOFI-AVENTIS GROUP (INCL SANOFI S,"University of California, Los AngelesUniversit...",135000,ContractContract,sanofi-aventis group (incl sanofi s
Sanofi,University of GeorgiaUniversity of GeorgiaUniv...,5475166,ContractContractContractContractContractContra...,sanofi
Sanofi (Foreign Parent Company),University of Colorado Denver,150000,Contract,sanofi (foreign parent company)
Sanofi Aventis Groupe,Duke University,712015,Monetary Gift,sanofi aventis groupe
Sanofi Aventis Recherche,Duke UniversityDuke University,14225699,Monetary GiftMonetary Gift,sanofi aventis recherche
"Sanofi Aventis, Inc.","Rutgers, the State University of New JerseyRut...",1855143,ContractContractContract,"sanofi aventis, inc."
Sanofi Oncology,University of Washington - Seattle,549522,Contract,sanofi oncology
Sanofi Pasteur,University of PittsburghUniversity of Pittsbur...,466714,ContractContractContractContractContract,sanofi pasteur
Sanofi Pasteur Inc.,University of PittsburghUniversity of Pittsbur...,241009,Monetary GiftMonetary GiftMonetary Gift,sanofi pasteur inc.
Sanofi US Services,Indiana University - Purdue University Indiana...,726165,ContractContract,sanofi us services
Sanofi US Services Inc.,"University of California, San Francisco",398264,Contract,sanofi us services inc.
"Sanofi US Services, Inc.",University of Michigan - Ann ArborUniversity o...,797896,ContractContract,"sanofi us services, inc."
Sanofi-Aventis,Purdue UniversityCase Western Reserve Universi...,904059,Monetary GiftContractContractContractContractC...,sanofi-aventis
Sanofi-Aventis Recerche,Duke UniversityDuke UniversityDuke UniversityD...,62106706,ContractMonetary GiftMonetary GiftMonetary Gift,sanofi-aventis recerche
Sanofi-Aventis Recherche,Duke UniversityDuke UniversityDuke UniversityD...,58520202,Monetary GiftMonetary GiftMonetary GiftMonetar...,sanofi-aventis recherche
Sanofi-Aventis Recherche & Developp,Oregon Health & Science UniversityOregon Healt...,1142537,ContractContract,sanofi-aventis recherche & developp
Sanofi-Aventis U.S. Inc.,University of Iowa,406000,Contract,sanofi-aventis u.s. inc.
Sanofi-aventis,Ohio State University (The)Ohio State Universi...,1923417,ContractContractContractContractContractContra...,sanofi-aventis

>Here's all the sanofi specific donations. Missing UVA, so there is potential. They also give a LOT. But how much exactly?

In [60]:
sanofi_money=france[mask]['Foreign Gift Amount'].sum()
sanofi_money

np.int64(161558438)

>Yeah that's a lot. More than UVA is currently getting

>Is this enough? Maybe I'll investigate Qatar too since they give the most out of any country.

In [75]:
gifts.loc[gifts['Country of Giftor']=='QATAR'].groupby(gifts['Giftor Name']).sum()[['Institution Name', 'Foreign Gift Amount', 'Gift Type']]

,Institution Name,Foreign Gift Amount,Gift Type
Giftor Name,,,
Al Faisal Holding Co,DePaul University,476485,Monetary Gift
"Ali,Afrah,Moosa Saleh",Northern Arizona University,1000,Monetary Gift
Anonymous #121,Yale University,284668,Contract
Aramco Services Co,Texas A&M University,336902,Contract
Community College of Qatar,Houston Community CollegeHouston Community Col...,9138938,ContractContract
"Construction Development Co, LLC",Pennsylvania State University (The),450906,Monetary Gift
Doha Film Institute,Northwestern UniversityNorthwestern University,600000,ContractContract
Embassy of Qatar,Georgetown UniversityGeorgetown University,292780,Monetary GiftMonetary Gift
Embassy of the State of Qatar,Georgetown UniversityGeorgetown UniversityFlor...,3390439,Monetary GiftMonetary GiftContractContractCont...
Embassy of the State of Qatar - Def,Western Michigan UniversityWestern Michigan Un...,40323,ContractContractContract
Embassy of the State of Qatar - Sec,Western Michigan University,16285,Contract
Emg of the State of Qatar Cultural,George Mason UniversityGeorge Mason University,813266,ContractContract
Government of Qatar,George Washington University,536795,Contract
Hamad Medical Corp,Cornell University,288968,Contract
Hamad Medical Corporation,University of Arizona (The)Purdue UniversityCo...,1967497,ContractMonetary GiftContractContractContract
Jasoor Institute,Georgetown UniversityGeorgetown UniversityGeor...,4514402,ContractContractContract
Josoor Institute,Georgetown University,494813,Contract
Maersk Oil,Texas A&M University,634950,Monetary Gift
Maersk Oil Qatar,Texas A&M University,801692,Monetary Gift
Moosa Saleh Ali Afrah,Northern Arizona University,1000,Monetary Gift
Ooredoo,Texas A&M University,249978,Monetary Gift
Primary Health Care Corporation,University of Colorado Denver,141685,Contract
Primary Healthcare Corp-Qatar,University of Colorado Denver,134938,Contract
QAPCO,Texas A&M UniversityTexas A&M UniversityTexas ...,1836093,Monetary GiftMonetary GiftMonetary GiftMonetar...
Qatar,Oregon State UniversityTexas A&M UniversityTex...,20212143,Monetary GiftContractContractContract
Qatar Airways,Arizona State UniversityArizona State Universi...,343957,ContractContractContractContractContract
Qatar Airways QCSC,Oregon State University,12416,Contract
Qatar Biomedical Research Institute,University of Iowa,344857,Contract
Qatar Computing Research Institute,Texas A&M University,995890,Monetary Gift
Qatar Embassy,DePaul UniversityDePaul University,622728,ContractContract
Qatar Environment & Energy Res Inst,University of Michigan - Ann Arbor,197250,Contract
Qatar Environmental & Energy Res In,Purdue University,328110,Monetary Gift
Qatar Environmntl & Energy Res Inst,Purdue University,299450,Monetary Gift
Qatar Founation,Texas A&M University,450596,Contract
Qatar Foundaiton,Texas A&M University,27800,Contract
Qatar Foundation,Georgetown UniversityGeorgetown UniversityGeor...,1165905872,ContractContractContractContractContractContra...
Qatar Foundation for Education,Oregon State UniversityCarnegie Mellon Univers...,373945215,ContractContractContractContractContractContract
Qatar Foundation/Qatar National Res,Cornell UniversityCornell UniversityCornell Un...,796197000,ContractContractContractContractContractContra...
Qatar Foundationq,Texas A&M University,87606,Contract
Qatar Foundaton,Texas A&M University,127639,Contract
Qatar Government,University of Colorado DenverUniversity of Col...,664214,ContractContractContract
Qatar Harvey Fund,Lamar UniversityLamar University,2308232,Monetary GiftMonetary Gift
Qatar Leadership Center,Georgetown UniversityDuke UniversityWilliam Ma...,3264236,ContractMonetary GiftContract
Qatar Nat'l Research Fund,University of Michigan - Ann ArborUniversity o...,189215,ContractContractContract
Qatar National Research,Carnegie Mellon UniversityCarnegie Mellon Univ...,4573226,ContractContractContractContractContractContract
Qatar National Research Foundation,Texas A&M UniversityTexas A&M UniversityTexas ...,11682998,ContractContractContractContractContractContra...
Qatar National Research Fund,Georgetown UniversityGeorgetown UniversityGeor...,79021705,ContractContractContractContractContractContra...
Qatar National Research Fund/Qatar,Northwestern UniversityNorthwestern University,233001,ContractContract
Qatar Natl Research Fund,University of Texas at Dallas,270504,Contract
Qatar Petroleum,Arizona State UniversityArizona State Universi...,726103,ContractContractContractContractContractContra...
Qatar Research Foundation,Texas A&M UniversityTexas A&M UniversityTexas ...,1691717,ContractContractContractContractContractContra...
Qatar Scholarship,University of Colorado Denver,870568,Contract
Qatar University,Emory UniversityUniversity of Illinois at Urba...,3482719,ContractContractContractContractContractContra...
Qatar University/Qatar National R.,Northwestern UniversityNorthwestern University,238455,ContractContract
Ras Girtas Power-Qatar,Texas A&M University,53429,Monetary Gift
RasGas Company Limited,Arizona State UniversityArizona State Universi...,1200850,ContractContractContractContractContractContra...
Rebuild Texas Fund,Houston Community College,300000,Monetary Gift
Shell Research & Tech-Qatar,Texas A&M University,27397,Monetary Gift
Sidra Medical and Research Center,Arizona State UniversityArizona State Universi...,594274,ContractContractContractContractContract
Supreme Cmte for Delivery & Legacy,Georgetown University,629375,Contract
Supreme Committee for Delivery & Le,Cornell UniversityCornell UniversityCornell Un...,4174819,ContractContractContract
Texas A&M/Qatar National Research,Northwestern UniversityNorthwestern University...,228955,ContractContractContract
The Qatar Foundation,University of Colorado BoulderUniversity of Co...,21850,Monetary GiftMonetary Gift
Weill Cornell Medical College/Qatar,Cornell University,508500,Contract

In [71]:
mask2= gifts['Giftor Name'].str.contains('Qatar Foundation')
gifts[mask2].groupby('Institution Name').sum()

,ID,OPEID,City,State,Foreign Gift Received Date,Foreign Gift Amount,Gift Type,Country of Giftor,Giftor Name
Institution Name,,,,,,,,,
Carnegie Mellon University,115424,1621000,PittsburghPittsburghPittsburghPittsburghPittsb...,PAPAPAPAPA,213678,373914113,ContractContractContractContractContract,QATARQATARQATARQATARQATAR,Qatar Foundation for EducationQatar Foundation...
Cornell University,196298,2711000,IthacaIthacaIthacaIthacaIthacaIthacaIthacaItha...,NYNYNYNYNYNYNYNYNYNY,425002,796197000,ContractContractContractContractContractContra...,QATARQATARQATARQATARQATARQATARQATARQATARQATARQ...,Qatar Foundation/Qatar National ResQatar Found...
Georgetown University,122957,1589500,WashingtonWashingtonWashingtonWashingtonWashin...,DCDCDCDCDCDCDCDCDCDCDC,471347,314161323,ContractContractContractContractContractContra...,QATARQATARQATARQATARQATARQATARQATARQATARQATARQ...,Qatar FoundationQatar FoundationQatar Foundati...
Georgia Institute of Technology,11412,156900,Atlanta,GA,42270,272915,Contract,QATAR,Qatar Foundation
Northwestern University,143123,2086800,EvanstonEvanstonEvanstonEvanstonEvanstonEvanst...,ILILILILILILILILILILILIL,513902,305556268,ContractContractContractContractContractContra...,QATARQATARQATARQATARQATARQATARQATARQATARQATARQ...,Qatar FoundationQatar FoundationQatar Foundati...
Oregon State University,22980,321000,Corvallis,OR,43830,31102,Contract,QATAR,Qatar Foundation for Education
Purdue University,13050,182500,West Lafayette,IN,42233,250000,Monetary Gift,QATAR,Qatar Foundation
Texas A&M University,5776235,82809600,College StationCollege StationCollege StationC...,TXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTX...,9788965,465726003,ContractContractContractContractContractContra...,QATARQATARQATARQATARQATARQATARQATARQATARQATARQ...,Qatar FoundationQatar FoundationQatar Foundati...
University of Colorado Boulder,20551,274000,BoulderBoulder,COCO,86664,21850,Monetary GiftMonetary Gift,QATARQATAR,The Qatar FoundationThe Qatar Foundation
University of Houston,25585,365200,Houston,TX,43507,92500,Monetary Gift,QATAR,Qatar Foundation
University of Michigan - Ann Arbor,84896,1162500,Ann ArborAnn ArborAnn ArborAnn ArborAnn Arbor,MIMIMIMIMI,210847,2246466,ContractContractContractContractMonetary Gift,QATARQATARQATARQATARQATAR,Qatar FoundationQatar FoundationQatar Foundati...
Virginia Commonwealth University,78548,1120500,RichmondRichmondRichmond,VAVAVA,129478,78285875,ContractContractContract,QATARQATARQATAR,Qatar FoundationQatar FoundationQatar Foundation

In [72]:
gifts['Foreign Gift Amount'].sum()

np.int64(16600515514)

>Using the same process as Sanofi, Qatar's national foundation gives to so many schools. It would be great to get into that pot, but it seems more difficult. There seems to be less of a pattern of which schools they give to, so there are probably more complicated politics at play. I'll stick to the research side of the money