In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

gifts=pd.read_csv('ForeignGifts_edu.csv')

In [22]:
pd.set_option('display.max_rows',100)
gifts_to_uva=gifts[gifts['Institution Name']=="University of Virginia"]

In [10]:
gifts_to_uva[['Country of Giftor','Foreign Gift Amount', 'Gift Type', 'Giftor Name']]

,Country of Giftor,Foreign Gift Amount,Gift Type,Giftor Name
26235,ENGLAND,3565,Monetary Gift,West Yorkshire Police
26236,ISRAEL,12265,Contract,CureTech Ltd
26237,ISRAEL,8187,Monetary Gift,Branco Weiss Institute
26238,ISRAEL,6437,Contract,NovoCure Ltd
26239,ISRAEL,216943,Contract,InSightec-Image Guide Treatment Ltd
26240,ISRAEL,12021,Contract,InSightec-Image Guide Treatment Ltd
26241,ISRAEL,55811,Contract,InSightec-Image Guide Treatment Ltd
26242,ISRAEL,10000,Monetary Gift,Atox Bio Ltd.
26243,ENGLAND,9825,Monetary Gift,TauRx Therapeutics Ltd
26244,ISRAEL,6979,Monetary Gift,US-Israel Binational Sci Fdn
26245,ISRAEL,5612,Monetary Gift,US-Israel Binational Sci Fdn
26246,BANGLADESH,310001,Monetary Gift,Intl Ctr for Diarrhoeal Disease
26247,ISRAEL,2650,Contract,BSP-Biological Signal Proc Ltd
26248,ENGLAND,68910,Monetary Gift,Kirkhouse Trust
26249,ENGLAND,321029,Monetary Gift,Charles Aid Foundation
26250,SWEDEN,1500027,Contract,AstraZeneca
26251,SWEDEN,7622,Contract,Orexo AB
26252,JAPAN,265970,Contract,"Honda R & D Co., LTD"
26253,KOREA,131534,Contract,Daegu Gyeongbuk Inst of Sci & Tech
26254,KOREA,249555,Contract,Hyundai Motor Company
26255,ENGLAND,53452,Monetary Gift,Kirkhouse Trust
26256,ENGLAND,300460,Monetary Gift,Charities Aid Foundation
26257,ENGLAND,65633,Monetary Gift,University of Newcastle
26258,SINGAPORE,500000,Monetary Gift,Rainbow Foundation
26259,BANGLADESH,275008,Monetary Gift,Intl. Cntr for Diarrihoeal Disease
26260,KOREA,318537,Contract,Hyundai Motor Company
26261,BANGLADESH,304450,Contract,Intrnl Centre Diarrheal Disease
26262,BANGLADESH,1077948,Contract,Intrnl Centre Diarrheal Disease
26263,BANGLADESH,498,Monetary Gift,Intrnl Centre Diarrheal Disease
26264,BANGLADESH,421278,Contract,Intl. Cntr for Diarrihoeal Disease
26265,THE NETHERLANDS,236681,Contract,Philips Healthcare
26266,ISRAEL,23500,Contract,Galmed Research & Development Ltd
26267,KOREA,41428,Contract,Korea Transport Institute
26268,BANGLADESH,31,Contract,Intl. Cntr for Diarrihoeal Disease
26269,ENGLAND,106196,Contract,University of Liverpool
26270,ENGLAND,3102,Contract,TauRx Therapeutics Ltd.
26271,ENGLAND,68082,Contract,Kirkhouse Trust
26272,ENGLAND,32996,Contract,London School of Economics
26273,ENGLAND,102662,Contract,GW Research Ltd.
26274,SWEDEN,1708021,Contract,AstraZeneca
26275,THE NETHERLANDS,195369,Contract,Genmab B.V.
26276,KOREA,113400,Contract,Daegu Gyeongbuk Inst of Sc& Tech
26277,SWEDEN,29970,Contract,Elekta Instrument AB
26278,BERMUDA,900000,Monetary Gift,Hemera Foundation
26279,KOREA,8333,Contract,Korea Automobile Testing & Research
26280,SWEDEN,5056,Contract,AutoLiv Development AB
26281,ENGLAND,22880,Contract,University of Newcastle
26282,SWEDEN,76695,Contract,Chalmers University of Technology
26283,ISRAEL,263250,Contract,InSightec-Image Guided Treatment Lt
26284,ENGLAND,211622,Monetary Gift,Charities Aid Foundation
26285,FINLAND,277515,Contract,Danisco Sweeteners Oy
26286,ENGLAND,65150,Contract,G. W. Research Ltd
26287,ENGLAND,8933,Contract,London School of Economics
26288,ENGLAND,20927,Monetary Gift,University of Newcastle
26289,ENGLAND,128195,Monetary Gift,Kirkhouse Trust
26290,FINLAND,7500,Contract,FKD Therapies Oy
26291,TANZANIA,640555,Contract,Haydom Lutheran Hospital
26292,FINLAND,370020,Contract,Danisco Sweeteners Oy
26293,RWANDA,284135,Contract,"Republic of Rwanda, Mintr of Health"
26294,ENGLAND,9750,Contract,Adelphi Group Limited
26295,ENGLAND,3071,Monetary Gift,Kirkhouse Trust
26296,GUERNSEY,500000,Monetary Gift,Harvest Group Holding
26297,FRANCE,113478,Contract,"Theraclion, S.A."
26298,ENGLAND,13344,Monetary Gift,Kirkhouse Trust
26299,BANGLADESH,339,Monetary Gift,Intnl Centre for Diarrhoeal Disease
26300,FRANCE,112470,Monetary Gift,Human Frontier Science Program
26301,ENGLAND,7850,Contract,GW Research Ltd
26302,FRANCE,5250,Contract,Biom 'Up
26303,TANZANIA,1100553,Contract,Haydom Lutheran Hospital d/b/a Hayd
26304,ENGLAND,6000,Contract,Emergent Countermeasures Intnl
26305,ENGLAND,8601,Monetary Gift,Kirkhouse Trust
26306,ENGLAND,35056,Contract,GW Research Ltd
26307,ENGLAND,20982,Contract,London School of Economics
26308,ENGLAND,215846,Monetary Gift,Charities Aid Foundation
26309,FRANCE,9350,Contract,Genfit
26310,ENGLAND,7184,Monetary Gift,Kirkhouse Trust
26311,ENGLAND,223,Monetary Gift,University of Newcastle
26312,BANGLADESH,919518,Contract,Intnl Centre for Diarrhoeal Disease
26313,ENGLAND,13519,Contract,GW Research Ltd
26314,FRANCE,9835,Contract,Genfit
26315,ENGLAND,15621,Monetary Gift,Kirkhouse Trust
26316,FINLAND,84376,Contract,Danisco Sweeteners Oy
26317,FINLAND,1493,Contract,FKD Therapies Oy
26318,FINLAND,9060,Contract,FKD Therapies Oy
26319,FINLAND,258420,Contract,Danisco Sweeteners Oy
26320,SWEDEN,207032,Contract,AutoLiv Development AB
26321,TANZANIA,1035339,Contract,Haydom Luther Hospital
26322,GUERNSEY,500000,Monetary Gift,Harvest Group Holding
26323,SWEDEN,207019,Contract,AutoLiv Development AB
26324,SINGAPORE,305000,Monetary Gift,Rainbow Foundation
26325,SWEDEN,166225,Contract,AutoLiv Development AB
26326,BANGLADESH,919518,Contract,International Centre for Diarrhoeal
26327,SWITZERLAND,1000000,Monetary Gift,Lawrence D/ Karin S Howell
26328,SWEDEN,99885,Contract,AutoLiv Development AB
26329,SWITZERLAND,1000000,Monetary Gift,Lawrence D & Karin S Howell
26330,GUERNSEY,500000,Monetary Gift,Harvest Group Holding (PTC Limited)
26331,THE NETHERLANDS,146810,Contract,Pantarhei Oncology BV
26332,THE NETHERLANDS,146810,Contract,Pantarhei Oncology BV

>Here, I'm making a new dataframe that is grouped by not only the country, but where else they donated to and how much. This is going to be perfect for data exploration.

In [17]:
country_to_school=gifts.groupby(['Country of Giftor','Institution Name']).sum()['Foreign Gift Amount']

In [ ]:
country_to_school=pd.DataFrame(country_to_school)
country_to_school[1:50]

#since this is long, we look at it in chunks

                                                                      Foreign Gift Amount
Country of Giftor Institution Name
AFGHANISTAN       Ohio University                                                  516102
                  University of Illinois at Urbana-Champaign                      1604589
AMERICAN SAMOA    University of Hawaii at Manoa                                   2338347
ANGOLA            University of Colorado Boulder                                   432482
                  University of Oklahoma                                           499908
ANTIGUA           Florida International University                                3435545
ARGENTINA         Brigham Young University                                        1750000
                  Columbia University in the City of New York                      280000
                  Harvard University                                              1258418
                  Johns Hopkins University                                          10425
                  Massachusetts Institute of Technology                           3727609
                  Stanford University                                              900000
                  University of Notre Dame                                         200000
                  University of Washington - Seattle                               337632
ARMENIA           Johns Hopkins University                                            300
AUSTRALIA         Arizona State University                                        1199900
                  California Institute of Technology                              2465432
                  Carnegie Mellon University                                      1148070
                  Catholic University of America (The)                            1307450
                  Columbia University in the City of New York                     1238597
                  Cornell University                                              2014431
                  Duke University                                                  849954
                  Emory University                                                 555184
                  George Mason University                                           44950
                  George Washington University                                     653557
                  Georgia Institute of Technology                                 1261164
                  Harvard University                                              6321092
                  Indiana University - Purdue University Indianap...              1480492
                  Johns Hopkins University                                        3849790
                  Kansas State University                                         1159330
                  Massachusetts Institute of Technology                           7505960
                  Michigan State University                                        709175
                  New Jersey Institute of Technology                              1240106
                  North Carolina State University                                  258653
                  Northeastern University                                       148355497
                  Northern Arizona University                                      403928
                  Ohio State University (The)                                     1092000
                  Oregon Health & Science University                               332197
                  Princeton University                                           12900000
                  Purdue University                                               1500000
                  Rensselaer Polytechnic Institute                                 300000
                  Stanford University                                             2604725
                  Texas Tech University                                           2250000
                  University of Alabama at Birmingham                              608019
                  University of Arizona (The)                                      916308
                  University of California, Berkeley                               812334
                  University of California, Davis                                 2363248
                  University of California, Los Angeles                           2320429
                  University of California, San Diego                             3207794

In [29]:
country_to_school.xs("AUSTRALIA",level="Country of Giftor")

                                                    Foreign Gift Amount
Institution Name
Arizona State University                                        1199900
California Institute of Technology                              2465432
Carnegie Mellon University                                      1148070
Catholic University of America (The)                            1307450
Columbia University in the City of New York                     1238597
Cornell University                                              2014431
Duke University                                                  849954
Emory University                                                 555184
George Mason University                                           44950
George Washington University                                     653557
Georgia Institute of Technology                                 1261164
Harvard University                                              6321092
Indiana University - Purdue University Indianap...              1480492
Johns Hopkins University                                        3849790
Kansas State University                                         1159330
Massachusetts Institute of Technology                           7505960
Michigan State University                                        709175
New Jersey Institute of Technology                              1240106
North Carolina State University                                  258653
Northeastern University                                       148355497
Northern Arizona University                                      403928
Ohio State University (The)                                     1092000
Oregon Health & Science University                               332197
Princeton University                                           12900000
Purdue University                                               1500000
Rensselaer Polytechnic Institute                                 300000
Stanford University                                             2604725
Texas Tech University                                           2250000
University of Alabama at Birmingham                              608019
University of Arizona (The)                                      916308
University of California, Berkeley                               812334
University of California, Davis                                 2363248
University of California, Los Angeles                           2320429
University of California, San Diego                             3207794
University of Chicago (The)                                     3000000
University of Colorado Boulder                                     1000
University of Colorado Colorado Springs                            2200
University of Florida                                           1106173
University of Georgia                                            770099
University of Illinois at Chicago                               4448217
University of Kentucky                                           250949
University of Louisville                                         150776
University of Maryland, College Park                             328770
University of Michigan - Ann Arbor                               965452
University of Notre Dame                                         875355
University of Pennsylvania                                       393199
University of Pittsburgh                                         136011
University of Rochester                                          324840
University of Southern California                              14400000
University of Texas MD Anderson Cancer Center                    578256
University of Texas at Austin                                   1397961
University of Washington - Seattle                               286135
Virginia Commonwealth University                                 371196
Westminster Theological Seminary                                  10323
Yale University                                                 3382524

>Wow, australia likes to give a lot of money to a lot of different schools. Specifically, they like to give to a lot of big research schools and they're pretty familiar with giving to virginia schools.

Next, seperate out for just australia and look to see who is giving. It's not helpful to talk to the country as a whole. Who specifically do we need to talk to?

In [44]:
australian_giftors=gifts.loc[gifts['Country of Giftor']=='AUSTRALIA'].groupby(gifts['Giftor Name']).sum()[['Institution Name', 'Foreign Gift Amount']]
australian_giftors.head(20)

,Institution Name,Foreign Gift Amount
Giftor Name,,
"ALLEN, C","University of California, Los Angeles",150
"ALONTE, SALLY","University of California, Los Angeles",25
"ANAND, SAURABH","University of California, Los Angeles",50
AUSTRALIAN HEALTH AND NUTRITION ASS,"University of California, San DiegoUniversity ...",347672
"Anand, Saurabh","University of California, Los Angeles",50
Anon. Donor #7,Yale University,281478
Anonymous #10,Yale University,591324
Anonymous #14,Yale University,346627
Anonymous #147,Yale University,1889095
Anonymous #59,Yale University,274000
Arthritis Austrailia,Georgia Institute of Technology,300000
Australian Catholic University,"University of California, San DiegoUniversity ...",1983302
Australian Graduate School of Manag,University of Pennsylvania,393199
Australian Ministry Foreign Affairs,Columbia University in the City of New York,209275
Australian Nat'l Low Emissions Coal,University of Texas at AustinUniversity of Tex...,781861
Australian National University,Northern Arizona UniversityNorthern Arizona Un...,302114
Australian Wool Innovation Limited,North Carolina State University,258653
"BAUKH, SIMON","University of California, Los Angeles",500
"BAUKH, SIMON M","University of California, Los Angeles",500
BCAL Diagnostics Pty Limited,University of Kentucky,250949

> After discovering some patterns in this data, I'm seeing a TON of money is going into health research (which is great since UVA has a huge health research department)

Only small donations though :(

Let's try france

In [49]:
france=gifts.loc[gifts['Country of Giftor']=='FRANCE'].groupby(gifts['Giftor Name']).sum()[['Institution Name', 'Foreign Gift Amount']]
france['giftor']=france.index
france

,Institution Name,Foreign Gift Amount,giftor
Giftor Name,,,
"""BUZZI, STEPHANE""",California Institute of Technology,5043,"""BUZZI, STEPHANE"""
"""KASPERSKI, TATIANA""",California Institute of Technology,586,"""KASPERSKI, TATIANA"""
"""RILEY, LEANNE""",California Institute of Technology,3556,"""RILEY, LEANNE"""
AAV Life,Cornell University,1189505,AAV Life
AB Science,University of Tennessee,370384,AB Science
...,...,...,...
"Yron, Lionel","University of California, Los Angeles",20,"Yron, Lionel"
Yves Saint Laurent SAS,"University of California, Los AngelesUniversit...",20000,Yves Saint Laurent SAS
Zodiac Data Systems,California Institute of Technology,3178,Zodiac Data Systems
"bioMerieux, Inc","Rutgers, the State University of New JerseyRut...",984977,"bioMerieux, Inc"
École polytechnique fédérale,California Institute of TechnologyCalifornia I...,34257,École polytechnique fédérale

In [ ]:
france['giftor']=france['giftor'].str.lower()
mask= france['giftor'].str.contains('sanofi')
france[mask]

,Institution Name,Foreign Gift Amount,giftor
Giftor Name,,,
SANOFI,University of GeorgiaUniversity of GeorgiaUniv...,7093879,sanofi
SANOFI PASTEUR,University of Wisconsin - Madison,610911,sanofi pasteur
SANOFI PASTEUR LIMITED,University of Colorado DenverUniversity of Col...,53015,sanofi pasteur limited
"SANOFI PHARMACEUTICALS, INC.",University of PennsylvaniaUniversity of Pennsy...,1063194,"sanofi pharmaceuticals, inc."
"SANOFI PHARMACEUTICALS,INC",University of PennsylvaniaUniversity of Pennsy...,215550,"sanofi pharmaceuticals,inc"
"SANOFI PHARMACEUTICALS,INC.",University of PennsylvaniaUniversity of Pennsy...,268072,"sanofi pharmaceuticals,inc."
SANOFI S.A.,"University of California, Los AngelesUniversit...",527281,sanofi s.a.
SANOFI SA,"University of California, Los Angeles",556983,sanofi sa
SANOFI-AVENTIS,California Institute of TechnologyCalifornia I...,434039,sanofi-aventis
SANOFI-AVENTIS GROUP (INCL SANOFI S,"University of California, Los AngelesUniversit...",135000,sanofi-aventis group (incl sanofi s
Sanofi,University of GeorgiaUniversity of GeorgiaUniv...,5475166,sanofi
Sanofi (Foreign Parent Company),University of Colorado Denver,150000,sanofi (foreign parent company)
Sanofi Aventis Groupe,Duke University,712015,sanofi aventis groupe
Sanofi Aventis Recherche,Duke UniversityDuke University,14225699,sanofi aventis recherche
"Sanofi Aventis, Inc.","Rutgers, the State University of New JerseyRut...",1855143,"sanofi aventis, inc."
Sanofi Oncology,University of Washington - Seattle,549522,sanofi oncology
Sanofi Pasteur,University of PittsburghUniversity of Pittsbur...,466714,sanofi pasteur
Sanofi Pasteur Inc.,University of PittsburghUniversity of Pittsbur...,241009,sanofi pasteur inc.
Sanofi US Services,Indiana University - Purdue University Indiana...,726165,sanofi us services
Sanofi US Services Inc.,"University of California, San Francisco",398264,sanofi us services inc.
"Sanofi US Services, Inc.",University of Michigan - Ann ArborUniversity o...,797896,"sanofi us services, inc."
Sanofi-Aventis,Purdue UniversityCase Western Reserve Universi...,904059,sanofi-aventis
Sanofi-Aventis Recerche,Duke UniversityDuke UniversityDuke UniversityD...,62106706,sanofi-aventis recerche
Sanofi-Aventis Recherche,Duke UniversityDuke UniversityDuke UniversityD...,58520202,sanofi-aventis recherche
Sanofi-Aventis Recherche & Developp,Oregon Health & Science UniversityOregon Healt...,1142537,sanofi-aventis recherche & developp
Sanofi-Aventis U.S. Inc.,University of Iowa,406000,sanofi-aventis u.s. inc.
Sanofi-aventis,Ohio State University (The)Ohio State Universi...,1923417,sanofi-aventis